GameBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.GameBucket.name}

GameBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref GameBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
            - s3:DeleteObject
          Resource: arn:aws:s3:::${self:custom.GameBucket.name}/*
