GameTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: GameTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: slug
        AttributeType: S
    KeySchema:
      - AttributeName: slug
        KeyType: HASH
    # use GSI for querying on non primary key, example:
    # GlobalSecondaryIndexes:
    #   - IndexName: uid
    #     KeySchema:
    #       - AttributeName: id
    #         KeyType: HASH
    #     Projection:
    #       ProjectionType: ALL
