RatingsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: RatingsTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: imdb_title_id
        AttributeType: N
      - AttributeName: UID
        AttributeType: S

    KeySchema:
      - AttributeName: imdb_title_id
        KeyType: HASH
      - AttributeName: UID
        KeyType: RANGE
