RatingsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: RatingsTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: imdb_title_id
        AttributeType: N
      - AttributeName: username
        AttributeType: S

    KeySchema:
      - AttributeName: imdb_title_id
        KeyType: HASH
      - AttributeName: username
        KeyType: RANGE

    GlobalSecondaryIndexes:
      - IndexName: username
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        Projection:
          ProjectionType: ALL
