ReactBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.ReactBucket.name}
    WebsiteConfiguration:
      IndexDocument: index.html
      ErrorDocument: index.html

ReactBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref ReactBucket
    PolicyDocument:
      Statement:
        - Sid: AllowBucketSync
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${self:custom.ReactBucket.name}
            - arn:aws:s3:::${self:custom.ReactBucket.name}/*
