ResetPasswordTokensTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ResetPasswordTokensTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: emailAddress
        AttributeType: S

    KeySchema:
      - AttributeName: emailAddress
        KeyType: HASH
