TciTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: TciTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: usernames
        AttributeType: S

    KeySchema:
      - AttributeName: usernames
        KeyType: HASH
