UserTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: UserTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: username
        AttributeType: S
      - AttributeName: email
        AttributeType: S
      - AttributeName: UID
        AttributeType: S

    KeySchema:
      - AttributeName: UID
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: username
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: email
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        Projection:
          ProjectionType: ALL
