UserTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: UserTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: username
        AttributeType: S
      - AttributeName: email
        AttributeType: S
      - AttributeName: uid
        AttributeType: S
    KeySchema:
      - AttributeName: email
        KeyType: HASH
    # use GSI for querying on non primary key, example:
    GlobalSecondaryIndexes:
      - IndexName: username
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: email
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: uid
        KeySchema:
          - AttributeName: uid
            KeyType: HASH
        Projection:
          ProjectionType: ALL
