UserTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: UserTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: username
        AttributeType: S
      - AttributeName: email
        AttributeType: S
    KeySchema:
      - AttributeName: email
        KeyType: HASH
    # use GSI for querying on non primary key, example:
    # GlobalSecondaryIndexes:
    #   - IndexName: uid
    #     KeySchema:
    #       - AttributeName: id
    #         KeyType: HASH
    #     Projection:
    #       ProjectionType: ALL
    GlobalSecondaryIndexes:
      - IndexName: username
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: email
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        Projection:
          ProjectionType: ALL
